// Snapshot from Datos_BDM_Extraidos.xlsx · sheet Rendimiento BDM

export type BdmStatus = 'Active' | 'Inactive'

export type BdmPerformanceEntry = {
  bdm: string
  status: BdmStatus
  month: string
  country: string
  netDeposit: number
  mibs: number
  activeIbs: number
  lots: number
  teamOffice: string
  previousRank: number
  ibActivationRate: number
}

export const BDM_PERFORMANCE_MONTHS = ['Jul', 'Jun'] as const

export const BDM_PERFORMANCE: BdmPerformanceEntry[] = [
  {
    bdm: 'Alejandro Granados',
    status: 'Active',
    month: 'Jun',
    country: 'México',
    netDeposit: 9951.24,
    mibs: 10,
    activeIbs: 2,
    lots: 67.75,
    teamOffice: 'México',
    previousRank: 1,
    ibActivationRate: 0.2,
  },
  {
    bdm: 'Danilo Romero',
    status: 'Active',
    month: 'Jun',
    country: 'Colombia',
    netDeposit: -2314.56,
    mibs: 5,
    activeIbs: 2,
    lots: 11.1,
    teamOffice: 'Colombia & Peru',
    previousRank: 6,
    ibActivationRate: 0.4,
  },
  {
    bdm: 'Gerardo Sanchez',
    status: 'Active',
    month: 'Jun',
    country: 'México',
    netDeposit: 595.61,
    mibs: 6,
    activeIbs: 2,
    lots: 53.43,
    teamOffice: 'México',
    previousRank: 2,
    ibActivationRate: 0.33,
  },
  {
    bdm: 'Joao Sandi',
    status: 'Active',
    month: 'Jun',
    country: 'Brazil',
    netDeposit: -79.13,
    mibs: 3,
    activeIbs: 1,
    lots: 5.38,
    teamOffice: 'LATAM South',
    previousRank: 7,
    ibActivationRate: 0.33,
  },
  {
    bdm: 'Joel Flores',
    status: 'Active',
    month: 'Jun',
    country: 'México',
    netDeposit: -21308.44,
    mibs: 3,
    activeIbs: 2,
    lots: 14.39,
    teamOffice: 'México',
    previousRank: 3,
    ibActivationRate: 0.67,
  },
  {
    bdm: 'Juan Tachack',
    status: 'Active',
    month: 'Jun',
    country: 'Colombia',
    netDeposit: 17103.0,
    mibs: 6,
    activeIbs: 4,
    lots: 27.57,
    teamOffice: 'Colombia & Peru',
    previousRank: 8,
    ibActivationRate: 0.67,
  },
  {
    bdm: 'Juliana Alonso',
    status: 'Active',
    month: 'Jun',
    country: 'Uruguay',
    netDeposit: -3108.3,
    mibs: 5,
    activeIbs: 3,
    lots: 18.33,
    teamOffice: 'Colombia & Peru',
    previousRank: 9,
    ibActivationRate: 0.6,
  },
  {
    bdm: 'María José Mangione',
    status: 'Active',
    month: 'Jun',
    country: 'Argentina',
    netDeposit: -7250.0,
    mibs: 0,
    activeIbs: 0,
    lots: 6.06,
    teamOffice: 'LATAM South',
    previousRank: 10,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Nicole Coronel',
    status: 'Active',
    month: 'Jun',
    country: 'Ecuador',
    netDeposit: -2507.31,
    mibs: 1,
    activeIbs: 1,
    lots: 0.17,
    teamOffice: 'Ecuador',
    previousRank: 12,
    ibActivationRate: 1.0,
  },
  {
    bdm: 'Rafael Caballero',
    status: 'Active',
    month: 'Jun',
    country: 'Colombia',
    netDeposit: 105356.79,
    mibs: 0,
    activeIbs: 1,
    lots: 8.24,
    teamOffice: 'Colombia & Peru',
    previousRank: 13,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Sergio Vargas',
    status: 'Active',
    month: 'Jun',
    country: 'Colombia',
    netDeposit: 51053.68,
    mibs: 6,
    activeIbs: 4,
    lots: 0.46,
    teamOffice: 'Colombia & Peru',
    previousRank: 14,
    ibActivationRate: 0.67,
  },
  {
    bdm: 'Yennifer Caballero',
    status: 'Active',
    month: 'Jun',
    country: 'Uruguay',
    netDeposit: 32398.89,
    mibs: 0,
    activeIbs: 0,
    lots: 20.57,
    teamOffice: 'LATAM South',
    previousRank: 16,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Antonio Perea',
    status: 'Inactive',
    month: 'Jun',
    country: 'Colombia',
    netDeposit: 6183.08,
    mibs: 0,
    activeIbs: 0,
    lots: 0.14,
    teamOffice: 'Colombia & Peru',
    previousRank: 4,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Carmen Jimenez',
    status: 'Active',
    month: 'Jun',
    country: 'Colombia',
    netDeposit: 2371.98,
    mibs: 6,
    activeIbs: 3,
    lots: 0.83,
    teamOffice: 'Colombia & Peru',
    previousRank: 5,
    ibActivationRate: 0.5,
  },
  {
    bdm: 'Yanina Blanco',
    status: 'Active',
    month: 'Jun',
    country: 'Uruguay',
    netDeposit: 300090.0,
    mibs: 0,
    activeIbs: 1,
    lots: 1980.0,
    teamOffice: 'LATAM South',
    previousRank: 17,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Alejandro Granados',
    status: 'Active',
    month: 'Jul',
    country: 'México',
    netDeposit: 129787.95,
    mibs: 0,
    activeIbs: 0,
    lots: 253.91,
    teamOffice: 'México',
    previousRank: 4,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Carmen Jimenez',
    status: 'Active',
    month: 'Jul',
    country: 'Colombia',
    netDeposit: 4289.71,
    mibs: 7,
    activeIbs: 3,
    lots: 15.98,
    teamOffice: 'Colombia & Peru',
    previousRank: 5,
    ibActivationRate: 0.43,
  },
  {
    bdm: 'Emanuel Diaz',
    status: 'Active',
    month: 'Jul',
    country: 'Colombia',
    netDeposit: 1400.52,
    mibs: 7,
    activeIbs: 2,
    lots: 0.0,
    teamOffice: 'Colombia & Peru',
    previousRank: 15,
    ibActivationRate: 0.29,
  },
  {
    bdm: 'Gerardo Sanchez',
    status: 'Active',
    month: 'Jul',
    country: 'México',
    netDeposit: -82240.94,
    mibs: 3,
    activeIbs: 0,
    lots: 156.77,
    teamOffice: 'México',
    previousRank: 7,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Joao Sandi',
    status: 'Active',
    month: 'Jul',
    country: 'Brazil',
    netDeposit: -7360.78,
    mibs: 5,
    activeIbs: 0,
    lots: 14.27,
    teamOffice: 'LATAM South',
    previousRank: 11,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Joel Flores',
    status: 'Active',
    month: 'Jul',
    country: 'México',
    netDeposit: 131449.75,
    mibs: 3,
    activeIbs: 0,
    lots: 221.97,
    teamOffice: 'México',
    previousRank: 10,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Juan Tachack',
    status: 'Active',
    month: 'Jul',
    country: 'Colombia',
    netDeposit: -41840.96,
    mibs: 9,
    activeIbs: 3,
    lots: 88.18,
    teamOffice: 'Colombia & Peru',
    previousRank: 3,
    ibActivationRate: 0.33,
  },
  {
    bdm: 'Juliana Alonso',
    status: 'Active',
    month: 'Jul',
    country: 'Uruguay',
    netDeposit: -3835.35,
    mibs: 2,
    activeIbs: 0,
    lots: 26.9,
    teamOffice: 'LATAM South',
    previousRank: 6,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Lucia Villalobos',
    status: 'Active',
    month: 'Jul',
    country: 'México',
    netDeposit: 3320.02,
    mibs: 8,
    activeIbs: 0,
    lots: 0.0,
    teamOffice: 'México',
    previousRank: 14,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Nicole Coronel',
    status: 'Active',
    month: 'Jul',
    country: 'Ecuador',
    netDeposit: 11831.19,
    mibs: 3,
    activeIbs: 0,
    lots: 67.25,
    teamOffice: 'Ecuador',
    previousRank: 12,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Rafael Caballero',
    status: 'Active',
    month: 'Jul',
    country: 'Colombia',
    netDeposit: -741.55,
    mibs: 1,
    activeIbs: 0,
    lots: 194.32,
    teamOffice: 'Colombia & Peru',
    previousRank: 9,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Sergio Vargas',
    status: 'Active',
    month: 'Jul',
    country: 'Colombia',
    netDeposit: 5562.9,
    mibs: 4,
    activeIbs: 1,
    lots: 224.97,
    teamOffice: 'Colombia & Peru',
    previousRank: 2,
    ibActivationRate: 0.25,
  },
  {
    bdm: 'Yanina Blanco',
    status: 'Active',
    month: 'Jul',
    country: 'Uruguay',
    netDeposit: 620126.82,
    mibs: 0,
    activeIbs: 0,
    lots: 6090.19,
    teamOffice: 'LATAM South',
    previousRank: 1,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Yennifer Caballero',
    status: 'Active',
    month: 'Jul',
    country: 'Uruguay',
    netDeposit: -3901.16,
    mibs: 0,
    activeIbs: 0,
    lots: 359.72,
    teamOffice: 'LATAM South',
    previousRank: 13,
    ibActivationRate: 0.0,
  },
  {
    bdm: 'Yesica Tovar',
    status: 'Inactive',
    month: 'Jul',
    country: 'Colombia',
    netDeposit: -106.47,
    mibs: 0,
    activeIbs: 0,
    lots: 11.71,
    teamOffice: 'Colombia & Peru',
    previousRank: 16,
    ibActivationRate: 0.0,
  },
]
